name: ğŸ§Ÿ Mutation testing

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

permissions:
  contents: read

env:
  CI: 1
  HUSKY: 0
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: ${{ github.ref == 'refs/heads/master' && 'pnpm' || '' }}
          # zizmor: ignore[cache-poisoning] caching restricted to trusted refs
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: ğŸ’¾ Cache mutation reports
        uses: actions/cache@v5.0.3
        with:
          path: ./packages/eslint-plugin-wyrm/reports/
          key: mutation-reports-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            mutation-reports-${{ github.ref_name }}-

      - name: â›ï¸ build
        run: pnpm run build
        working-directory: ./packages/eslint-plugin-wyrm/

      - name: ğŸ§Ÿ Run mutation testing
        run: pnpm run test:mut
        working-directory: ./packages/eslint-plugin-wyrm/
